project_name: dimg

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
