project_name: dimg

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

brews:
  - name: dimg
    description: "TUI for docker pull"
    github:
      owner: kohbis
      name: homebrew-dimg
    folder: Formula
    homepage: "https://github.com/kohbis/dimg"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    install: |
      bin.install "dimg"
